spring:
  profiles:
    active: sql, common, wx
  messages:
    encoding: UTF-8

server:
  port: 8088

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    com.sugo.wx:  DEBUG
    com.sugo:  ERROR