spring:
  profiles:
    active: sql, common, admin, wx
  messages:
    encoding: UTF-8
  main:
    allow-bean-definition-overriding: true

server:
  port: 8088

logging:
  config: classpath:logback-spring.xml

