package com.sugo.sql.dao;

import com.sugo.sql.entity.SugoCouponUser;
import com.sugo.sql.entity.SugoCouponUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SugoCouponUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_coupon_user
     *
     * @mbg.generated
     */
    long countByExample(SugoCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_coupon_user
     *
     * @mbg.generated
     */
    int deleteByExample(SugoCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_coupon_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_coupon_user
     *
     * @mbg.generated
     */
    int insert(SugoCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_coupon_user
     *
     * @mbg.generated
     */
    int insertSelective(SugoCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_coupon_user
     *
     * @mbg.generated
     */
    SugoCouponUser selectOneByExample(SugoCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_coupon_user
     *
     * @mbg.generated
     */
    SugoCouponUser selectOneByExampleSelective(@Param("example") SugoCouponUserExample example, @Param("selective") SugoCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_coupon_user
     *
     * @mbg.generated
     */
    List<SugoCouponUser> selectByExampleSelective(@Param("example") SugoCouponUserExample example, @Param("selective") SugoCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_coupon_user
     *
     * @mbg.generated
     */
    List<SugoCouponUser> selectByExample(SugoCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_coupon_user
     *
     * @mbg.generated
     */
    SugoCouponUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SugoCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_coupon_user
     *
     * @mbg.generated
     */
    SugoCouponUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_coupon_user
     *
     * @mbg.generated
     */
    SugoCouponUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_coupon_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SugoCouponUser record, @Param("example") SugoCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_coupon_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SugoCouponUser record, @Param("example") SugoCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SugoCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SugoCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SugoCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}