package com.sugo.sql.dao;

import com.sugo.sql.entity.SugoAdmin;
import com.sugo.sql.entity.SugoAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SugoAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_admin
     *
     * @mbg.generated
     */
    long countByExample(SugoAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_admin
     *
     * @mbg.generated
     */
    int deleteByExample(SugoAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_admin
     *
     * @mbg.generated
     */
    int insert(SugoAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_admin
     *
     * @mbg.generated
     */
    int insertSelective(SugoAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_admin
     *
     * @mbg.generated
     */
    SugoAdmin selectOneByExample(SugoAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_admin
     *
     * @mbg.generated
     */
    SugoAdmin selectOneByExampleSelective(@Param("example") SugoAdminExample example, @Param("selective") SugoAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_admin
     *
     * @mbg.generated
     */
    List<SugoAdmin> selectByExampleSelective(@Param("example") SugoAdminExample example, @Param("selective") SugoAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_admin
     *
     * @mbg.generated
     */
    List<SugoAdmin> selectByExample(SugoAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_admin
     *
     * @mbg.generated
     */
    SugoAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SugoAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_admin
     *
     * @mbg.generated
     */
    SugoAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_admin
     *
     * @mbg.generated
     */
    SugoAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SugoAdmin record, @Param("example") SugoAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SugoAdmin record, @Param("example") SugoAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SugoAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SugoAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SugoAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}