package com.sugo.sql.dao;

import com.sugo.sql.entity.SugoAd;
import com.sugo.sql.entity.SugoAdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SugoAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_ad
     *
     * @mbg.generated
     */
    long countByExample(SugoAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_ad
     *
     * @mbg.generated
     */
    int deleteByExample(SugoAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_ad
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_ad
     *
     * @mbg.generated
     */
    int insert(SugoAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_ad
     *
     * @mbg.generated
     */
    int insertSelective(SugoAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_ad
     *
     * @mbg.generated
     */
    SugoAd selectOneByExample(SugoAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_ad
     *
     * @mbg.generated
     */
    SugoAd selectOneByExampleSelective(@Param("example") SugoAdExample example, @Param("selective") SugoAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_ad
     *
     * @mbg.generated
     */
    List<SugoAd> selectByExampleSelective(@Param("example") SugoAdExample example, @Param("selective") SugoAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_ad
     *
     * @mbg.generated
     */
    List<SugoAd> selectByExample(SugoAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_ad
     *
     * @mbg.generated
     */
    SugoAd selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SugoAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_ad
     *
     * @mbg.generated
     */
    SugoAd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_ad
     *
     * @mbg.generated
     */
    SugoAd selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_ad
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SugoAd record, @Param("example") SugoAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_ad
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SugoAd record, @Param("example") SugoAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SugoAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SugoAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SugoAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}