package com.sugo.sql.dao;

import com.sugo.sql.entity.SugoTopic;
import com.sugo.sql.entity.SugoTopicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SugoTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_topic
     *
     * @mbg.generated
     */
    long countByExample(SugoTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_topic
     *
     * @mbg.generated
     */
    int deleteByExample(SugoTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_topic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_topic
     *
     * @mbg.generated
     */
    int insert(SugoTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_topic
     *
     * @mbg.generated
     */
    int insertSelective(SugoTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_topic
     *
     * @mbg.generated
     */
    SugoTopic selectOneByExample(SugoTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_topic
     *
     * @mbg.generated
     */
    SugoTopic selectOneByExampleSelective(@Param("example") SugoTopicExample example, @Param("selective") SugoTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_topic
     *
     * @mbg.generated
     */
    SugoTopic selectOneByExampleWithBLOBs(SugoTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_topic
     *
     * @mbg.generated
     */
    List<SugoTopic> selectByExampleSelective(@Param("example") SugoTopicExample example, @Param("selective") SugoTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_topic
     *
     * @mbg.generated
     */
    List<SugoTopic> selectByExampleWithBLOBs(SugoTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_topic
     *
     * @mbg.generated
     */
    List<SugoTopic> selectByExample(SugoTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_topic
     *
     * @mbg.generated
     */
    SugoTopic selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SugoTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_topic
     *
     * @mbg.generated
     */
    SugoTopic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_topic
     *
     * @mbg.generated
     */
    SugoTopic selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_topic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SugoTopic record, @Param("example") SugoTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_topic
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") SugoTopic record, @Param("example") SugoTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_topic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SugoTopic record, @Param("example") SugoTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SugoTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(SugoTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SugoTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SugoTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}