package com.sugo.sql.dao;

import com.sugo.sql.entity.SugoNotice;
import com.sugo.sql.entity.SugoNoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SugoNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_notice
     *
     * @mbg.generated
     */
    long countByExample(SugoNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_notice
     *
     * @mbg.generated
     */
    int deleteByExample(SugoNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_notice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_notice
     *
     * @mbg.generated
     */
    int insert(SugoNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_notice
     *
     * @mbg.generated
     */
    int insertSelective(SugoNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_notice
     *
     * @mbg.generated
     */
    SugoNotice selectOneByExample(SugoNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_notice
     *
     * @mbg.generated
     */
    SugoNotice selectOneByExampleSelective(@Param("example") SugoNoticeExample example, @Param("selective") SugoNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_notice
     *
     * @mbg.generated
     */
    List<SugoNotice> selectByExampleSelective(@Param("example") SugoNoticeExample example, @Param("selective") SugoNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_notice
     *
     * @mbg.generated
     */
    List<SugoNotice> selectByExample(SugoNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_notice
     *
     * @mbg.generated
     */
    SugoNotice selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SugoNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_notice
     *
     * @mbg.generated
     */
    SugoNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_notice
     *
     * @mbg.generated
     */
    SugoNotice selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_notice
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SugoNotice record, @Param("example") SugoNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_notice
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SugoNotice record, @Param("example") SugoNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SugoNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SugoNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_notice
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SugoNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_notice
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}