package com.sugo.sql.dao;

import com.sugo.sql.entity.SugoLog;
import com.sugo.sql.entity.SugoLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SugoLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_log
     *
     * @mbg.generated
     */
    long countByExample(SugoLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_log
     *
     * @mbg.generated
     */
    int deleteByExample(SugoLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_log
     *
     * @mbg.generated
     */
    int insert(SugoLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_log
     *
     * @mbg.generated
     */
    int insertSelective(SugoLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_log
     *
     * @mbg.generated
     */
    SugoLog selectOneByExample(SugoLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_log
     *
     * @mbg.generated
     */
    SugoLog selectOneByExampleSelective(@Param("example") SugoLogExample example, @Param("selective") SugoLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_log
     *
     * @mbg.generated
     */
    List<SugoLog> selectByExampleSelective(@Param("example") SugoLogExample example, @Param("selective") SugoLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_log
     *
     * @mbg.generated
     */
    List<SugoLog> selectByExample(SugoLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_log
     *
     * @mbg.generated
     */
    SugoLog selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SugoLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_log
     *
     * @mbg.generated
     */
    SugoLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_log
     *
     * @mbg.generated
     */
    SugoLog selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SugoLog record, @Param("example") SugoLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SugoLog record, @Param("example") SugoLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SugoLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SugoLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_log
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SugoLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_log
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}