package com.sugo.sql.dao;

import com.sugo.sql.entity.SugoPermission;
import com.sugo.sql.entity.SugoPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SugoPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_permission
     *
     * @mbg.generated
     */
    long countByExample(SugoPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_permission
     *
     * @mbg.generated
     */
    int deleteByExample(SugoPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_permission
     *
     * @mbg.generated
     */
    int insert(SugoPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_permission
     *
     * @mbg.generated
     */
    int insertSelective(SugoPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_permission
     *
     * @mbg.generated
     */
    SugoPermission selectOneByExample(SugoPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_permission
     *
     * @mbg.generated
     */
    SugoPermission selectOneByExampleSelective(@Param("example") SugoPermissionExample example, @Param("selective") SugoPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_permission
     *
     * @mbg.generated
     */
    List<SugoPermission> selectByExampleSelective(@Param("example") SugoPermissionExample example, @Param("selective") SugoPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_permission
     *
     * @mbg.generated
     */
    List<SugoPermission> selectByExample(SugoPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_permission
     *
     * @mbg.generated
     */
    SugoPermission selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SugoPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_permission
     *
     * @mbg.generated
     */
    SugoPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_permission
     *
     * @mbg.generated
     */
    SugoPermission selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SugoPermission record, @Param("example") SugoPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SugoPermission record, @Param("example") SugoPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SugoPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SugoPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SugoPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}