package com.sugo.sql.dao;

import com.sugo.sql.entity.SugoRegion;
import com.sugo.sql.entity.SugoRegionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SugoRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_region
     *
     * @mbg.generated
     */
    long countByExample(SugoRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_region
     *
     * @mbg.generated
     */
    int deleteByExample(SugoRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_region
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_region
     *
     * @mbg.generated
     */
    int insert(SugoRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_region
     *
     * @mbg.generated
     */
    int insertSelective(SugoRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_region
     *
     * @mbg.generated
     */
    SugoRegion selectOneByExample(SugoRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_region
     *
     * @mbg.generated
     */
    SugoRegion selectOneByExampleSelective(@Param("example") SugoRegionExample example, @Param("selective") SugoRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_region
     *
     * @mbg.generated
     */
    List<SugoRegion> selectByExampleSelective(@Param("example") SugoRegionExample example, @Param("selective") SugoRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_region
     *
     * @mbg.generated
     */
    List<SugoRegion> selectByExample(SugoRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_region
     *
     * @mbg.generated
     */
    SugoRegion selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SugoRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_region
     *
     * @mbg.generated
     */
    SugoRegion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_region
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SugoRegion record, @Param("example") SugoRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_region
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SugoRegion record, @Param("example") SugoRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SugoRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SugoRegion record);
}