package com.sugo.sql.dao;

import com.sugo.sql.entity.SugoCollect;
import com.sugo.sql.entity.SugoCollectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SugoCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_collect
     *
     * @mbg.generated
     */
    long countByExample(SugoCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_collect
     *
     * @mbg.generated
     */
    int deleteByExample(SugoCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_collect
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_collect
     *
     * @mbg.generated
     */
    int insert(SugoCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_collect
     *
     * @mbg.generated
     */
    int insertSelective(SugoCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_collect
     *
     * @mbg.generated
     */
    SugoCollect selectOneByExample(SugoCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_collect
     *
     * @mbg.generated
     */
    SugoCollect selectOneByExampleSelective(@Param("example") SugoCollectExample example, @Param("selective") SugoCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_collect
     *
     * @mbg.generated
     */
    List<SugoCollect> selectByExampleSelective(@Param("example") SugoCollectExample example, @Param("selective") SugoCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_collect
     *
     * @mbg.generated
     */
    List<SugoCollect> selectByExample(SugoCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_collect
     *
     * @mbg.generated
     */
    SugoCollect selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SugoCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_collect
     *
     * @mbg.generated
     */
    SugoCollect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_collect
     *
     * @mbg.generated
     */
    SugoCollect selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_collect
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SugoCollect record, @Param("example") SugoCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_collect
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SugoCollect record, @Param("example") SugoCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SugoCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SugoCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SugoCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}