package com.sugo.sql.dao;

import com.sugo.sql.entity.SugoCart;
import com.sugo.sql.entity.SugoCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SugoCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_cart
     *
     * @mbg.generated
     */
    long countByExample(SugoCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_cart
     *
     * @mbg.generated
     */
    int deleteByExample(SugoCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_cart
     *
     * @mbg.generated
     */
    int insert(SugoCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_cart
     *
     * @mbg.generated
     */
    int insertSelective(SugoCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_cart
     *
     * @mbg.generated
     */
    SugoCart selectOneByExample(SugoCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_cart
     *
     * @mbg.generated
     */
    SugoCart selectOneByExampleSelective(@Param("example") SugoCartExample example, @Param("selective") SugoCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_cart
     *
     * @mbg.generated
     */
    List<SugoCart> selectByExampleSelective(@Param("example") SugoCartExample example, @Param("selective") SugoCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_cart
     *
     * @mbg.generated
     */
    List<SugoCart> selectByExample(SugoCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_cart
     *
     * @mbg.generated
     */
    SugoCart selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SugoCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_cart
     *
     * @mbg.generated
     */
    SugoCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_cart
     *
     * @mbg.generated
     */
    SugoCart selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_cart
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SugoCart record, @Param("example") SugoCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_cart
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SugoCart record, @Param("example") SugoCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SugoCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SugoCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SugoCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}