package com.sugo.sql.dao;

import com.sugo.sql.entity.SugoUser;
import com.sugo.sql.entity.SugoUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SugoUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_user
     *
     * @mbg.generated
     */
    long countByExample(SugoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_user
     *
     * @mbg.generated
     */
    int deleteByExample(SugoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_user
     *
     * @mbg.generated
     */
    int insert(SugoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_user
     *
     * @mbg.generated
     */
    int insertSelective(SugoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_user
     *
     * @mbg.generated
     */
    SugoUser selectOneByExample(SugoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_user
     *
     * @mbg.generated
     */
    SugoUser selectOneByExampleSelective(@Param("example") SugoUserExample example, @Param("selective") SugoUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_user
     *
     * @mbg.generated
     */
    List<SugoUser> selectByExampleSelective(@Param("example") SugoUserExample example, @Param("selective") SugoUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_user
     *
     * @mbg.generated
     */
    List<SugoUser> selectByExample(SugoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_user
     *
     * @mbg.generated
     */
    SugoUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SugoUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_user
     *
     * @mbg.generated
     */
    SugoUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_user
     *
     * @mbg.generated
     */
    SugoUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SugoUser record, @Param("example") SugoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SugoUser record, @Param("example") SugoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SugoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SugoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SugoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}