package com.sugo.sql.dao;

import com.sugo.sql.entity.SugoRole;
import com.sugo.sql.entity.SugoRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SugoRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_role
     *
     * @mbg.generated
     */
    long countByExample(SugoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_role
     *
     * @mbg.generated
     */
    int deleteByExample(SugoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_role
     *
     * @mbg.generated
     */
    int insert(SugoRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_role
     *
     * @mbg.generated
     */
    int insertSelective(SugoRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_role
     *
     * @mbg.generated
     */
    SugoRole selectOneByExample(SugoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_role
     *
     * @mbg.generated
     */
    SugoRole selectOneByExampleSelective(@Param("example") SugoRoleExample example, @Param("selective") SugoRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_role
     *
     * @mbg.generated
     */
    List<SugoRole> selectByExampleSelective(@Param("example") SugoRoleExample example, @Param("selective") SugoRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_role
     *
     * @mbg.generated
     */
    List<SugoRole> selectByExample(SugoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_role
     *
     * @mbg.generated
     */
    SugoRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SugoRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_role
     *
     * @mbg.generated
     */
    SugoRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_role
     *
     * @mbg.generated
     */
    SugoRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SugoRole record, @Param("example") SugoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SugoRole record, @Param("example") SugoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SugoRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SugoRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_role
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SugoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_role
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}