package com.sugo.sql.dao;

import com.sugo.sql.entity.SugoGroupon;
import com.sugo.sql.entity.SugoGrouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SugoGrouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_groupon
     *
     * @mbg.generated
     */
    long countByExample(SugoGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_groupon
     *
     * @mbg.generated
     */
    int deleteByExample(SugoGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_groupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_groupon
     *
     * @mbg.generated
     */
    int insert(SugoGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_groupon
     *
     * @mbg.generated
     */
    int insertSelective(SugoGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_groupon
     *
     * @mbg.generated
     */
    SugoGroupon selectOneByExample(SugoGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_groupon
     *
     * @mbg.generated
     */
    SugoGroupon selectOneByExampleSelective(@Param("example") SugoGrouponExample example, @Param("selective") SugoGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_groupon
     *
     * @mbg.generated
     */
    List<SugoGroupon> selectByExampleSelective(@Param("example") SugoGrouponExample example, @Param("selective") SugoGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_groupon
     *
     * @mbg.generated
     */
    List<SugoGroupon> selectByExample(SugoGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_groupon
     *
     * @mbg.generated
     */
    SugoGroupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SugoGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_groupon
     *
     * @mbg.generated
     */
    SugoGroupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_groupon
     *
     * @mbg.generated
     */
    SugoGroupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_groupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SugoGroupon record, @Param("example") SugoGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_groupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SugoGroupon record, @Param("example") SugoGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_groupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SugoGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_groupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SugoGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_groupon
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SugoGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_groupon
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}