package com.sugo.sql.dao;

import com.sugo.sql.entity.SugoSystem;
import com.sugo.sql.entity.SugoSystemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SugoSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_system
     *
     * @mbg.generated
     */
    long countByExample(SugoSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_system
     *
     * @mbg.generated
     */
    int deleteByExample(SugoSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_system
     *
     * @mbg.generated
     */
    int insert(SugoSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_system
     *
     * @mbg.generated
     */
    int insertSelective(SugoSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_system
     *
     * @mbg.generated
     */
    SugoSystem selectOneByExample(SugoSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_system
     *
     * @mbg.generated
     */
    SugoSystem selectOneByExampleSelective(@Param("example") SugoSystemExample example, @Param("selective") SugoSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_system
     *
     * @mbg.generated
     */
    List<SugoSystem> selectByExampleSelective(@Param("example") SugoSystemExample example, @Param("selective") SugoSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_system
     *
     * @mbg.generated
     */
    List<SugoSystem> selectByExample(SugoSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_system
     *
     * @mbg.generated
     */
    SugoSystem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SugoSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_system
     *
     * @mbg.generated
     */
    SugoSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_system
     *
     * @mbg.generated
     */
    SugoSystem selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_system
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SugoSystem record, @Param("example") SugoSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_system
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SugoSystem record, @Param("example") SugoSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SugoSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SugoSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_system
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SugoSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_system
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}