package com.sugo.sql.dao;

import com.sugo.sql.entity.SugoSearchHistory;
import com.sugo.sql.entity.SugoSearchHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SugoSearchHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_search_history
     *
     * @mbg.generated
     */
    long countByExample(SugoSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_search_history
     *
     * @mbg.generated
     */
    int deleteByExample(SugoSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_search_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_search_history
     *
     * @mbg.generated
     */
    int insert(SugoSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_search_history
     *
     * @mbg.generated
     */
    int insertSelective(SugoSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_search_history
     *
     * @mbg.generated
     */
    SugoSearchHistory selectOneByExample(SugoSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_search_history
     *
     * @mbg.generated
     */
    SugoSearchHistory selectOneByExampleSelective(@Param("example") SugoSearchHistoryExample example, @Param("selective") SugoSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_search_history
     *
     * @mbg.generated
     */
    List<SugoSearchHistory> selectByExampleSelective(@Param("example") SugoSearchHistoryExample example, @Param("selective") SugoSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_search_history
     *
     * @mbg.generated
     */
    List<SugoSearchHistory> selectByExample(SugoSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_search_history
     *
     * @mbg.generated
     */
    SugoSearchHistory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SugoSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_search_history
     *
     * @mbg.generated
     */
    SugoSearchHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_search_history
     *
     * @mbg.generated
     */
    SugoSearchHistory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_search_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SugoSearchHistory record, @Param("example") SugoSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_search_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SugoSearchHistory record, @Param("example") SugoSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SugoSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SugoSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_search_history
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SugoSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_search_history
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}