package com.sugo.sql.dao;

import com.sugo.sql.entity.SugoComment;
import com.sugo.sql.entity.SugoCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SugoCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_comment
     *
     * @mbg.generated
     */
    long countByExample(SugoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_comment
     *
     * @mbg.generated
     */
    int deleteByExample(SugoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_comment
     *
     * @mbg.generated
     */
    int insert(SugoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_comment
     *
     * @mbg.generated
     */
    int insertSelective(SugoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_comment
     *
     * @mbg.generated
     */
    SugoComment selectOneByExample(SugoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_comment
     *
     * @mbg.generated
     */
    SugoComment selectOneByExampleSelective(@Param("example") SugoCommentExample example, @Param("selective") SugoComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_comment
     *
     * @mbg.generated
     */
    List<SugoComment> selectByExampleSelective(@Param("example") SugoCommentExample example, @Param("selective") SugoComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_comment
     *
     * @mbg.generated
     */
    List<SugoComment> selectByExample(SugoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_comment
     *
     * @mbg.generated
     */
    SugoComment selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SugoComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_comment
     *
     * @mbg.generated
     */
    SugoComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_comment
     *
     * @mbg.generated
     */
    SugoComment selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SugoComment record, @Param("example") SugoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SugoComment record, @Param("example") SugoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SugoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SugoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SugoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}