package com.sugo.sql.dao;

import com.sugo.sql.entity.SugoGoodsAttribute;
import com.sugo.sql.entity.SugoGoodsAttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SugoGoodsAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_attribute
     *
     * @mbg.generated
     */
    long countByExample(SugoGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByExample(SugoGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_attribute
     *
     * @mbg.generated
     */
    int insert(SugoGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_attribute
     *
     * @mbg.generated
     */
    int insertSelective(SugoGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_attribute
     *
     * @mbg.generated
     */
    SugoGoodsAttribute selectOneByExample(SugoGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_attribute
     *
     * @mbg.generated
     */
    SugoGoodsAttribute selectOneByExampleSelective(@Param("example") SugoGoodsAttributeExample example, @Param("selective") SugoGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_attribute
     *
     * @mbg.generated
     */
    List<SugoGoodsAttribute> selectByExampleSelective(@Param("example") SugoGoodsAttributeExample example, @Param("selective") SugoGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_attribute
     *
     * @mbg.generated
     */
    List<SugoGoodsAttribute> selectByExample(SugoGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_attribute
     *
     * @mbg.generated
     */
    SugoGoodsAttribute selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SugoGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_attribute
     *
     * @mbg.generated
     */
    SugoGoodsAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_attribute
     *
     * @mbg.generated
     */
    SugoGoodsAttribute selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SugoGoodsAttribute record, @Param("example") SugoGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SugoGoodsAttribute record, @Param("example") SugoGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SugoGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SugoGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SugoGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}