package com.sugo.sql.dao;

import com.sugo.sql.entity.SugoFootprint;
import com.sugo.sql.entity.SugoFootprintExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SugoFootprintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_footprint
     *
     * @mbg.generated
     */
    long countByExample(SugoFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_footprint
     *
     * @mbg.generated
     */
    int deleteByExample(SugoFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_footprint
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_footprint
     *
     * @mbg.generated
     */
    int insert(SugoFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_footprint
     *
     * @mbg.generated
     */
    int insertSelective(SugoFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_footprint
     *
     * @mbg.generated
     */
    SugoFootprint selectOneByExample(SugoFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_footprint
     *
     * @mbg.generated
     */
    SugoFootprint selectOneByExampleSelective(@Param("example") SugoFootprintExample example, @Param("selective") SugoFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_footprint
     *
     * @mbg.generated
     */
    List<SugoFootprint> selectByExampleSelective(@Param("example") SugoFootprintExample example, @Param("selective") SugoFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_footprint
     *
     * @mbg.generated
     */
    List<SugoFootprint> selectByExample(SugoFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_footprint
     *
     * @mbg.generated
     */
    SugoFootprint selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SugoFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_footprint
     *
     * @mbg.generated
     */
    SugoFootprint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_footprint
     *
     * @mbg.generated
     */
    SugoFootprint selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_footprint
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SugoFootprint record, @Param("example") SugoFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_footprint
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SugoFootprint record, @Param("example") SugoFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SugoFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SugoFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_footprint
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SugoFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_footprint
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}