package com.sugo.sql.dao;

import com.sugo.sql.entity.SugoGoodsProduct;
import com.sugo.sql.entity.SugoGoodsProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SugoGoodsProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_product
     *
     * @mbg.generated
     */
    long countByExample(SugoGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_product
     *
     * @mbg.generated
     */
    int deleteByExample(SugoGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_product
     *
     * @mbg.generated
     */
    int insert(SugoGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_product
     *
     * @mbg.generated
     */
    int insertSelective(SugoGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_product
     *
     * @mbg.generated
     */
    SugoGoodsProduct selectOneByExample(SugoGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_product
     *
     * @mbg.generated
     */
    SugoGoodsProduct selectOneByExampleSelective(@Param("example") SugoGoodsProductExample example, @Param("selective") SugoGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_product
     *
     * @mbg.generated
     */
    List<SugoGoodsProduct> selectByExampleSelective(@Param("example") SugoGoodsProductExample example, @Param("selective") SugoGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_product
     *
     * @mbg.generated
     */
    List<SugoGoodsProduct> selectByExample(SugoGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_product
     *
     * @mbg.generated
     */
    SugoGoodsProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SugoGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_product
     *
     * @mbg.generated
     */
    SugoGoodsProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_product
     *
     * @mbg.generated
     */
    SugoGoodsProduct selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SugoGoodsProduct record, @Param("example") SugoGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SugoGoodsProduct record, @Param("example") SugoGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SugoGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SugoGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SugoGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}