package com.sugo.sql.dao;

import com.sugo.sql.entity.SugoOrderGoods;
import com.sugo.sql.entity.SugoOrderGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SugoOrderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_order_goods
     *
     * @mbg.generated
     */
    long countByExample(SugoOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_order_goods
     *
     * @mbg.generated
     */
    int deleteByExample(SugoOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_order_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_order_goods
     *
     * @mbg.generated
     */
    int insert(SugoOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_order_goods
     *
     * @mbg.generated
     */
    int insertSelective(SugoOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_order_goods
     *
     * @mbg.generated
     */
    SugoOrderGoods selectOneByExample(SugoOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_order_goods
     *
     * @mbg.generated
     */
    SugoOrderGoods selectOneByExampleSelective(@Param("example") SugoOrderGoodsExample example, @Param("selective") SugoOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_order_goods
     *
     * @mbg.generated
     */
    List<SugoOrderGoods> selectByExampleSelective(@Param("example") SugoOrderGoodsExample example, @Param("selective") SugoOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_order_goods
     *
     * @mbg.generated
     */
    List<SugoOrderGoods> selectByExample(SugoOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_order_goods
     *
     * @mbg.generated
     */
    SugoOrderGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SugoOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_order_goods
     *
     * @mbg.generated
     */
    SugoOrderGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_order_goods
     *
     * @mbg.generated
     */
    SugoOrderGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_order_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SugoOrderGoods record, @Param("example") SugoOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_order_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SugoOrderGoods record, @Param("example") SugoOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SugoOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SugoOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SugoOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}