package com.sugo.sql.dao;

import com.sugo.sql.entity.SugoBrand;
import com.sugo.sql.entity.SugoBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SugoBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_brand
     *
     * @mbg.generated
     */
    long countByExample(SugoBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_brand
     *
     * @mbg.generated
     */
    int deleteByExample(SugoBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_brand
     *
     * @mbg.generated
     */
    int insert(SugoBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_brand
     *
     * @mbg.generated
     */
    int insertSelective(SugoBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_brand
     *
     * @mbg.generated
     */
    SugoBrand selectOneByExample(SugoBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_brand
     *
     * @mbg.generated
     */
    SugoBrand selectOneByExampleSelective(@Param("example") SugoBrandExample example, @Param("selective") SugoBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_brand
     *
     * @mbg.generated
     */
    List<SugoBrand> selectByExampleSelective(@Param("example") SugoBrandExample example, @Param("selective") SugoBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_brand
     *
     * @mbg.generated
     */
    List<SugoBrand> selectByExample(SugoBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_brand
     *
     * @mbg.generated
     */
    SugoBrand selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SugoBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_brand
     *
     * @mbg.generated
     */
    SugoBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_brand
     *
     * @mbg.generated
     */
    SugoBrand selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_brand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SugoBrand record, @Param("example") SugoBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_brand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SugoBrand record, @Param("example") SugoBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SugoBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SugoBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SugoBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sugo_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}